version: '3.7'
services:
  # iris container
  iris:
    image: coffee:v3
    init: true
    container_name: iris
    hostname: iris
    ports:
    - "8881:1972"
    environment: 
    - ISC_DATA_DIRECTORY=/iris-shared/durable
    volumes:
    - type: bind
      source: ./durable/compose
      target: /iris-shared

  # web gateway container
  webgateway:
    image: containers.intersystems.com/intersystems/webgateway:2023.1.0.229.0
    init: true
    container_name: webgateway
    hostname: webgateway
    ports:
    - "8882:80"
    - "8883:443"
    environment:
    - ISC_DATA_DIRECTORY=/webgateway-shared/durable
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - type: bind
      source: ./webgateway
      target: /webgateway-shared

