/// Use or operation of this code is subject to acceptance of the license available in the code repository for this code.
/// 
Class Demo.tempCoffeemaker Extends (%Persistent, Demo.coffeemaker)
{

Storage Default
{
<Data name="tempCoffeemakerDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Name</Value>
</Value>
<Value name="3">
<Value>Brand</Value>
</Value>
<Value name="4">
<Value>Color</Value>
</Value>
<Value name="5">
<Value>NumCups</Value>
</Value>
<Value name="6">
<Value>Price</Value>
</Value>
<Value name="7">
<Value>Img</Value>
</Value>
</Data>
<DataLocation>^Demo.tempCoffeemakerD</DataLocation>
<DefaultData>tempCoffeemakerDefaultData</DefaultData>
<IdLocation>^Demo.tempCoffeemakerD</IdLocation>
<IndexLocation>^Demo.tempCoffeemakerI</IndexLocation>
<StreamLocation>^Demo.tempCoffeemakerS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
